//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.AppointmentLogs = new HashSet<AppointmentLog>();
            this.PatientPrescriptions = new HashSet<PatientPrescription>();
        }
    
        public int AppointmentId { get; set; }
        public string AppointmentNo { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<decimal> Period { get; set; }
        public int StatusId { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentLog> AppointmentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientPrescription> PatientPrescriptions { get; set; }
    }
}
