//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentLog
    {
        public System.Guid VisitLogId { get; set; }
        public int AppointmentId { get; set; }
        public string LogType { get; set; }
        public string LogValue { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
