//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicPractice
    {
        public int ClinicId { get; set; }
        public int PracticeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Practice Practice { get; set; }
    }
}
