//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clinic()
        {
            this.ClinicPractices = new HashSet<ClinicPractice>();
            this.PatientsInvoices = new HashSet<PatientsInvoice>();
        }
    
        public int ClinicId { get; set; }
        public string ClinicNo { get; set; }
        public string ClinicName_en { get; set; }
        public string ClinicName_ar { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Floor { get; set; }
        public string Room { get; set; }
        public string Phone { get; set; }
        public string Ext { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicPractice> ClinicPractices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientsInvoice> PatientsInvoices { get; set; }
    }
}
