//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyContractCoverage
    {
        public int CoverageId { get; set; }
        public int ContractId { get; set; }
        public int ClassId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> TPID { get; set; }
        public Nullable<double> CompanyPrice { get; set; }
    
        public virtual CompanyClass CompanyClass { get; set; }
        public virtual CompanyContract CompanyContract { get; set; }
        public virtual Service Service { get; set; }
        public virtual TreatmentProgram TreatmentProgram { get; set; }
    }
}
