//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyContractPatientShare
    {
        public int CompanyContractId { get; set; }
        public int CompanyClassId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ShareType { get; set; }
        public Nullable<double> FixedPercentage { get; set; }
        public Nullable<double> FixedAmount { get; set; }
        public Nullable<double> MinShared { get; set; }
        public Nullable<double> MaxShared { get; set; }
    }
}
