//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMREntities : DbContext
    {
        public EMREntities()
            : base("name=EMREntities")
        {
        }

        public EMREntities(string connectionString)
            : base(connectionString)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
    
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointmentLog> AppointmentLogs { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BranchUser> BranchUsers { get; set; }
        public virtual DbSet<BranchWorkingHour> BranchWorkingHours { get; set; }
        public virtual DbSet<ClinicPractice> ClinicPractices { get; set; }
        public virtual DbSet<Clinic> Clinics { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyClass> CompanyClasses { get; set; }
        public virtual DbSet<CompanyContractCoverage> CompanyContractCoverages { get; set; }
        public virtual DbSet<CompanyContractPatientShare> CompanyContractPatientShares { get; set; }
        public virtual DbSet<CompanyContractPrice> CompanyContractPrices { get; set; }
        public virtual DbSet<CompanyContract> CompanyContracts { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<GroupBranch> GroupBranches { get; set; }
        public virtual DbSet<GroupPermission> GroupPermissions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<InvoiceTemplate> InvoiceTemplates { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<LookupType> LookupTypes { get; set; }
        public virtual DbSet<PatientFinancialDetail> PatientFinancialDetails { get; set; }
        public virtual DbSet<PatientPrescription> PatientPrescriptions { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientsInvoiceItem> PatientsInvoiceItems { get; set; }
        public virtual DbSet<PatientsInvoice> PatientsInvoices { get; set; }
        public virtual DbSet<PatientsInvoicesPayment> PatientsInvoicesPayments { get; set; }
        public virtual DbSet<PatientsLocal> PatientsLocals { get; set; }
        public virtual DbSet<PatientsMedicalHistory> PatientsMedicalHistories { get; set; }
        public virtual DbSet<PatientTPlan> PatientTPlans { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Practice> Practices { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemTimeZone> SystemTimeZones { get; set; }
        public virtual DbSet<TPlanLog> TPlanLogs { get; set; }
        public virtual DbSet<TreatmentProgram> TreatmentPrograms { get; set; }
        public virtual DbSet<TreatmentProgramsService> TreatmentProgramsServices { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_Appointment> vw_Appointment { get; set; }
        public virtual DbSet<vw_Branch> vw_Branch { get; set; }
        public virtual DbSet<vw_Clinic> vw_Clinic { get; set; }
        public virtual DbSet<vw_ClinicPractice> vw_ClinicPractice { get; set; }
        public virtual DbSet<vw_CompaniesInvoices> vw_CompaniesInvoices { get; set; }
        public virtual DbSet<vw_Company> vw_Company { get; set; }
        public virtual DbSet<vw_CompanyContractPrice> vw_CompanyContractPrice { get; set; }
        public virtual DbSet<vw_ContractCoverage> vw_ContractCoverage { get; set; }
        public virtual DbSet<vw_EventLogs> vw_EventLogs { get; set; }
        public virtual DbSet<vw_GroupBranch> vw_GroupBranch { get; set; }
        public virtual DbSet<vw_InvoicePayments> vw_InvoicePayments { get; set; }
        public virtual DbSet<vw_Invoices> vw_Invoices { get; set; }
        public virtual DbSet<vw_InvoiceTreatmentProgramServices> vw_InvoiceTreatmentProgramServices { get; set; }
        public virtual DbSet<vw_Location> vw_Location { get; set; }
        public virtual DbSet<vw_Patient> vw_Patient { get; set; }
        public virtual DbSet<vw_PatientSharedPricelist> vw_PatientSharedPricelist { get; set; }
        public virtual DbSet<vw_Prescription> vw_Prescription { get; set; }
        public virtual DbSet<vw_Provider> vw_Provider { get; set; }
        public virtual DbSet<vw_Service> vw_Service { get; set; }
        public virtual DbSet<vw_TreatmentPlan> vw_TreatmentPlan { get; set; }
        public virtual DbSet<vw_TreatmentProgram> vw_TreatmentProgram { get; set; }
        public virtual DbSet<vw_TreatmentProgramsService> vw_TreatmentProgramsService { get; set; }
        public virtual DbSet<vw_User> vw_User { get; set; }
        public virtual DbSet<vw_UserGroupBranch> vw_UserGroupBranch { get; set; }
        public virtual DbSet<vw_UsersPermission> vw_UsersPermission { get; set; }
    }
}
