//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTemplate
    {
        public int TemplateId { get; set; }
        public string TemplateName { get; set; }
        public string TextDirection { get; set; }
        public string PrinterType { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
