//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.PatientFinancialDetails = new HashSet<PatientFinancialDetail>();
            this.PatientsInvoices = new HashSet<PatientsInvoice>();
            this.PatientsLocals = new HashSet<PatientsLocal>();
        }
    
        public int PatientID { get; set; }
        public string PatientNumber { get; set; }
        public Nullable<int> MartialStatus { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public string Email { get; set; }
        public Nullable<int> Occupation { get; set; }
        public Nullable<int> Relationship { get; set; }
        public string RelativeFullName { get; set; }
        public string RelativeMobile { get; set; }
        public string RelativePhone { get; set; }
        public string RelativeEmail { get; set; }
        public string RelativeAddress { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<double> SpecialDiscount { get; set; }
        public Nullable<int> CompanyName { get; set; }
        public Nullable<int> Policy { get; set; }
        public string MemberID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Lookup Lookup1 { get; set; }
        public virtual Lookup Lookup2 { get; set; }
        public virtual Lookup Lookup3 { get; set; }
        public virtual Lookup Lookup4 { get; set; }
        public virtual Lookup Lookup5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientFinancialDetail> PatientFinancialDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientsInvoice> PatientsInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientsLocal> PatientsLocals { get; set; }
    }
}
