//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsLocal
    {
        public int PatientLocalID { get; set; }
        public int PatientID { get; set; }
        public int LanguageId { get; set; }
        public string FirstName { get; set; }
        public string FatherName { get; set; }
        public string GrandfatherName { get; set; }
        public string FamilyName { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
