//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.CompanyContractCoverages = new HashSet<CompanyContractCoverage>();
            this.CompanyContractPrices = new HashSet<CompanyContractPrice>();
            this.TreatmentProgramsServices = new HashSet<TreatmentProgramsService>();
        }
    
        public int ServiceId { get; set; }
        public string ServiceNo { get; set; }
        public string ServiceName_en { get; set; }
        public string ServiceName_ar { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public Nullable<double> ServiceCost { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public bool IsEnable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyContractCoverage> CompanyContractCoverages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyContractPrice> CompanyContractPrices { get; set; }
        public virtual Practice Practice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentProgramsService> TreatmentProgramsServices { get; set; }
    }
}
