//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemTimeZone
    {
        public byte SystemTimeZoneId { get; set; }
        public string TimeZoneDifference { get; set; }
        public string TimeZone_en { get; set; }
        public string TimeZone_ar { get; set; }
    }
}
