//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentProgramsService
    {
        public int TPServiceId { get; set; }
        public int ServiceId { get; set; }
        public int TPID { get; set; }
        public int Qty { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual TreatmentProgram TreatmentProgram { get; set; }
    }
}
