//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Appointment
    {
        public string Name_en { get; set; }
        public string Name_ar { get; set; }
        public string ProviderName { get; set; }
        public Nullable<bool> IsProvider { get; set; }
        public Nullable<int> UserId { get; set; }
        public int LanguageId { get; set; }
        public string PatientName { get; set; }
        public int AppointmentId { get; set; }
        public string AppointmentNo { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<decimal> Period { get; set; }
        public int StatusId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
        public string BranchName_en { get; set; }
        public string BranchName_ar { get; set; }
        public string PatientNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    }
}
