//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Branch
    {
        public int BranchId { get; set; }
        public string BranchName_en { get; set; }
        public string BranchName_ar { get; set; }
        public string Description { get; set; }
        public string TimeZone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public string FaxNo { get; set; }
        public string CityName_en { get; set; }
        public string CityName_ar { get; set; }
        public string CountryName_en { get; set; }
        public string CountryName_ar { get; set; }
    }
}
