//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Company
    {
        public int CompanyId { get; set; }
        public string CompanyNameEn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Type { get; set; }
        public string CompanyNameAr { get; set; }
        public string Name_en { get; set; }
        public string Name_ar { get; set; }
    }
}
