//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CompanyContractPrice
    {
        public int ContractId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> TPID { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public Nullable<double> TPPrice { get; set; }
        public int IsCustom { get; set; }
        public string ServiceName_en { get; set; }
        public string ServiceName_ar { get; set; }
        public string ProgramName_en { get; set; }
        public string ProgramName_ar { get; set; }
        public string TPPracticeName_en { get; set; }
        public string TPPracticeName_ar { get; set; }
        public string SPracticeName_en { get; set; }
        public string SPracticeName_ar { get; set; }
    }
}
