//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ContractCoverage
    {
        public int ContractId { get; set; }
        public int ClassId { get; set; }
        public string ServiceName_en { get; set; }
        public string ServiceName_ar { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string ProgramName_en { get; set; }
        public string ProgramName_ar { get; set; }
        public Nullable<int> TPID { get; set; }
        public int CoverageId { get; set; }
        public string ServiceNo { get; set; }
        public string ProgramNo { get; set; }
    }
}
