//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Patient
    {
        public string PatientNumber { get; set; }
        public Nullable<int> MartialStatus { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public string Email { get; set; }
        public Nullable<int> Occupation { get; set; }
        public Nullable<int> Relationship { get; set; }
        public string RelativeFullName { get; set; }
        public string RelativeMobile { get; set; }
        public string RelativePhone { get; set; }
        public string RelativeEmail { get; set; }
        public string RelativeAddress { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<double> SpecialDiscount { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNameAr { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> Policy { get; set; }
        public string MemberID { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string FirstName { get; set; }
        public string FatherName { get; set; }
        public string GrandfatherName { get; set; }
        public string FamilyName { get; set; }
        public string LanguageName { get; set; }
        public string LanguageCode { get; set; }
        public int PatientID { get; set; }
        public string Name_en { get; set; }
        public string Name_ar { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public string AppointmentNo { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<decimal> Period { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Notes { get; set; }
        public string Status_en { get; set; }
        public string Status_ar { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
    }
}
