//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Prescription
    {
        public int PrescriptionId { get; set; }
        public string AppointmentNo { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public string MedicineCode { get; set; }
        public string MedicineName { get; set; }
        public string Dosage { get; set; }
        public Nullable<int> FrequencyUnit { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> DurationUnit { get; set; }
        public string Duration { get; set; }
        public string Comments { get; set; }
    }
}
