//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Provider
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string ClinicName_en { get; set; }
        public string ClinicName_ar { get; set; }
        public string ClinicNo { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public string PracticeName_en { get; set; }
        public string PracticeNo { get; set; }
        public string PracticeName_ar { get; set; }
        public int PracticeId { get; set; }
    }
}
