//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Service
    {
        public int ServiceId { get; set; }
        public string ServiceNo { get; set; }
        public string ServiceName_en { get; set; }
        public string ServiceName_ar { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public Nullable<double> ServiceCost { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public bool IsEnable { get; set; }
        public string PracticeName_en { get; set; }
        public string PracticeName_ar { get; set; }
    }
}
