//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TreatmentProgram
    {
        public int TPID { get; set; }
        public string ProgramNo { get; set; }
        public string ProgramName_en { get; set; }
        public string ProgramName_ar { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<double> TPPrice { get; set; }
        public string PracticeName_en { get; set; }
        public string PracticeName_ar { get; set; }
        public string PracticeNo { get; set; }
    }
}
