//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TreatmentPlan
    {
        public int TPlanLogId { get; set; }
        public Nullable<int> TreatmentPlanId { get; set; }
        public string Problem { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public bool IsProvider { get; set; }
        public string ProviderName { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Status { get; set; }
        public string Name_en { get; set; }
        public string Name_ar { get; set; }
        public int LookupId { get; set; }
    }
}
