//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UsersPermission
    {
        public string ModuleName { get; set; }
        public int PermissionId { get; set; }
        public string ModuleGroup { get; set; }
        public string PermissionName { get; set; }
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public string PermissionTab { get; set; }
    }
}
