//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserGroupBranch
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string Username { get; set; }
        public bool Calendar { get; set; }
        public bool IsProvider { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public bool IsEnable { get; set; }
        public string GroupName { get; set; }
        public int GroupId { get; set; }
        public int BranchId { get; set; }
        public string BranchName_en { get; set; }
    }
}
